index_route:
  path: /
  defaults: { _controller: 'App\Controllers\IndexController::indexAction' }

admin_route:
  path: /admin
  defaults: { _controller: 'App\Controllers\AdminController::indexAction' }

task_created:
  path: /task/created
  defaults: { _controller: 'App\Controllers\TaskController::createdAction' }

task_update:
  path: /task/update/{id}
  defaults: { _controller: 'App\Controllers\TaskController::updateAction' }


task_save:
  path: /task/save
  defaults: { _controller: 'App\Controllers\TaskController::saveAction' }
task_save_id:
  path: /task/save/{id}
  defaults: { _controller: 'App\Controllers\TaskController::saveIdAction' }

api_route:
  path: /api
  defaults: { _controller: 'App\Controllers\ApiController::getAction' }
  methods:  GET

page_route:
  path: /page/{alias}
  defaults: { _controller: 'App\Controllers\PageController::showAction' }
